//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meta_CodeTable
    {
        public int ID { get; set; }
        public string CodeName { get; set; }
        public string TableName { get; set; }
        public int DataSort { get; set; }
        public string GBCode { get; set; }
        public Nullable<int> BaseTable { get; set; }
        public string BasePath { get; set; }
        public string TextProperty { get; set; }
        public string ValueProperty { get; set; }
        public string OrderProperty { get; set; }
        public Nullable<double> CurrentVersion { get; set; }
        public Nullable<double> EditVersion { get; set; }
        public string Description { get; set; }
        public int Deleted { get; set; }
        public string CkType { get; set; }
    }
}
