//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Code_School
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string UserID { get; set; }
        public int DistrictID { get; set; }
        public Nullable<int> TownsID { get; set; }
        public string SchoolMasterName { get; set; }
        public string SchoolAddres { get; set; }
        public string SchoolTelephone { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string ImgUrl { get; set; }
        public string WebSite { get; set; }
        public Nullable<System.DateTime> IsHotTime { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string CodeName { get; set; }
        public string schoolTypeNo { get; set; }
    }
}
